import { Request, Response } from "express";
import { validationResult } from "express-validator";
import { WesternHoroscopeService } from "../services/WesternHoroscopeService";
import { HoroscopeService } from "../services/HoroscopeService";
import { AstroCalculator } from "../core/AstroCalculator";
import { BirthChartCalculator } from "../core/BirthChartCalculator";
import { TimeUtil } from "../utils/TimeUtil";
import { PdfService } from "../services/PdfService";
import { PlanetName, ZodiacName } from "../types/enums";
import fs from "fs";
import path from "path";

const logFile = path.join(process.cwd(), "public", "debug.log");
const log = (msg: string) => {
  try {
    fs.appendFileSync(logFile, `[Controller] ${msg}\n`);
  } catch (e) {}
};

export class HoroscopeController {
  public static async generateHoroscope(req: Request, res: Response): Promise<void> {
    try {
      // 1. Validate Request
      const errors = validationResult(req);
      if (!errors.isEmpty()) {
        res.status(400).json({ errors: errors.array() });
        return;
      }

      const { name, day, month, year, hour, minute, place, latitude, longitude, timezone } = req.body;

      log(`Received request for ${name}`);
      // 2. Fetch Horoscope Data
      const birthDetails = {
        name,
        day: parseInt(day),
        month: parseInt(month),
        year: parseInt(year),
        hour: parseInt(hour),
        minute: parseInt(minute),
        place,
        latitude: parseFloat(latitude),
        longitude: parseFloat(longitude),
        timezone: parseFloat(timezone)
      };

      // Uses Western calculation now
      log("Calling WesternHoroscopeService...");
      const horoscopeData = await WesternHoroscopeService.getWesternHoroscope(birthDetails);
      log("WesternHoroscopeService returned.");

      // 3. Prepare PDF Data
      const pdfData = {
        name,
        birthDetails: {
          dob: `${day}/${month}/${year}`,
          tob: `${hour}:${minute}`,
          place,
          lat: parseFloat(latitude),
          lon: parseFloat(longitude),
          timezone: parseFloat(timezone),
        },
        horoscope: horoscopeData,
        company: {
          name: "Jemsoft Astrology",
          info: "Providing accurate Vedic Astrology reports based on ancient wisdom.",
          email: "support@jemsoft.com",
          landline: "022-12345678",
          mobile: "+91-9876543210",
          domainUrl: "www.jemsoftastrology.com",
          footerLink: "Generated by Jemsoft Astrology Engine",
          logoUrl: "https://via.placeholder.com/150", 
        },
      };

      // 4. Generate PDF
      log("Generating PDF...");
      const pdfUrl = await PdfService.generateHoroscopePdf(pdfData);
      log(`PDF Generated: ${pdfUrl}`);

      // 5. Send Response
      res.json({
        success: true,
        message: "Horoscope generated successfully",
        pdfUrl
      });

    } catch (error) {
            console.error(error);
            res.status(500).json({ success: false, message: "Internal Server Error" });
        }
    }

    public async generateMiniHoroscope(req: Request, res: Response) {
        log("[Controller] Mini PDF Request");
        try {
            const body = req.body;
            // Basic Validation handled by route validators or here
            
            // Calculate Vedic Data needed for the PDF
            // We can reuse HoroscopeService or calculator directly.
            // For "Mini", we need Planets and Ascendant.
            
            // Reconstruct birthDetails for Service
            // We need a Time object for BirthChartCalculator
            const time = TimeUtil.normalizeTime({
                year: parseInt(body.year),
                month: parseInt(body.month),
                day: parseInt(body.day),
                hour: parseInt(body.hour),
                minute: parseInt(body.min),
                second: 0,
                location: {
                    name: body.place,
                    latitude: parseFloat(body.lat),
                    longitude: parseFloat(body.lon),
                    timezone: body.tzone.toString()
                }
            });
            
            // Fetch Vedic Data (Clean Array)
            const rawPlanets = BirthChartCalculator.getAllPlanetPositions(time);
            
            // Ascendant calculation (separately if not in rawPlanets, but usually handled via AstroCalculator for Asc)
            // getAllPlanetPositions returns Sun-Ketu. Ascendant is separate.
            const ascendantAngle = AstroCalculator.getAscendantLongitude(time);
            const ascendantSign = AstroCalculator.getZodiacSignFromLongitude(ascendantAngle);
            const ascendantNak = AstroCalculator.getConstellationFromLongitude(ascendantAngle);
            
            const ascendant = {
                 name: 'Ascendant',
                 shortName: 'As',
                 signId: getSignId(String(ascendantSign.name)),
                 signName: ascendantSign.name,
                 degree: ascendantAngle.totalDegrees,
                 degreeInSign: ascendantSign.degreesInSign.totalDegrees,
                 nakshatra: ascendantNak.name
            };

            // Transform Planets
            const planets = rawPlanets.map(p => ({
                name: PlanetName[p.planet],
                shortName: PlanetName[p.planet].substring(0,2),
                signId: getSignId(String(p.sign.name)),
                signName: p.sign.name,
                degree: p.longitude.totalDegrees, // Total
                degreeInSign: p.sign.degreesInSign.totalDegrees,
                nakshatra: p.constellation.name
            }));
            
            // Add Ascendant to planets list if needed for table, or keep separate
            planets.unshift(ascendant);

            const pdfData = {
                ...body,
                planets,
                ascendant
            };

            const pdfUrl = await PdfService.generateMiniPdf(pdfData);
            
            res.json({
                status: true,
                pdf_url: `${req.protocol}://${req.get('host')}${pdfUrl}`
            });


        } catch (error) {
            log(`[Controller] Error: ${error}`);
            res.status(500).json({ status: false, message: "Error generating PDF" });
        }
    }
}

// Helper
function getSignId(signName: string): number {
    const signs = ["Aries", "Taurus", "Gemini", "Cancer", "Leo", "Virgo", "Libra", "Scorpio", "Sagittarius", "Capricorn", "Aquarius", "Pisces"];
    return signs.indexOf(signName) + 1;
}
